# 项目的启动端口
server:
  port: 8888

spring:
  threads:
    virtual:
      enabled: true
  application:
    # 定义项目名称
    name: damageViewer
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    # mysql数据源
    username: root
    password: mysql3306
    url: jdbc:mysql://127.0.0.1:3306/default_table?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: AuthHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml